
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nofit
 */
public class form_kasir extends javax.swing.JFrame {

    /**
     * Creates new form form_kasir
     */
    public form_kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rujak1 = new javax.swing.JRadioButton();
        tahutek1 = new javax.swing.JRadioButton();
        tahulontong1 = new javax.swing.JRadioButton();
        blendrang1 = new javax.swing.JRadioButton();
        nasibantingan1 = new javax.swing.JRadioButton();
        tahugenjrot1 = new javax.swing.JRadioButton();
        tahutek = new javax.swing.JTextField();
        rujak = new javax.swing.JTextField();
        blendrang = new javax.swing.JTextField();
        tahulontong = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        nasibantingan = new javax.swing.JTextField();
        escaon = new javax.swing.JTextField();
        kopi = new javax.swing.JTextField();
        BTT = new javax.swing.JTextField();
        BR = new javax.swing.JTextField();
        BBT = new javax.swing.JTextField();
        BTL = new javax.swing.JTextField();
        BTG = new javax.swing.JTextField();
        BNB = new javax.swing.JTextField();
        MEC = new javax.swing.JTextField();
        MK = new javax.swing.JTextField();
        kopi1 = new javax.swing.JRadioButton();
        escaon1 = new javax.swing.JRadioButton();
        tehtawar1 = new javax.swing.JRadioButton();
        aqua1 = new javax.swing.JRadioButton();
        esoyen1 = new javax.swing.JRadioButton();
        espisangijo1 = new javax.swing.JRadioButton();
        aqua = new javax.swing.JTextField();
        tehtawar = new javax.swing.JTextField();
        espisangijo = new javax.swing.JTextField();
        esoyen = new javax.swing.JTextField();
        MA = new javax.swing.JTextField();
        MTT = new javax.swing.JTextField();
        MEPI = new javax.swing.JTextField();
        MEO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tahugenjrot = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        bt_total = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        bt_kembalian = new javax.swing.JButton();
        kembalian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        exit = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        rujak1.setText("Rujak");
        rujak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rujak1ActionPerformed(evt);
            }
        });
        getContentPane().add(rujak1);
        rujak1.setBounds(50, 190, 140, 30);

        tahutek1.setText("Tahu Tek");
        tahutek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahutek1ActionPerformed(evt);
            }
        });
        getContentPane().add(tahutek1);
        tahutek1.setBounds(50, 240, 140, 30);

        tahulontong1.setText("Tahu Lontong");
        tahulontong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahulontong1ActionPerformed(evt);
            }
        });
        getContentPane().add(tahulontong1);
        tahulontong1.setBounds(50, 290, 150, 30);

        blendrang1.setText("Blendrang Tewel");
        blendrang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blendrang1ActionPerformed(evt);
            }
        });
        getContentPane().add(blendrang1);
        blendrang1.setBounds(50, 340, 140, 30);

        nasibantingan1.setText("Nasi Bantingan");
        nasibantingan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasibantingan1ActionPerformed(evt);
            }
        });
        getContentPane().add(nasibantingan1);
        nasibantingan1.setBounds(50, 390, 130, 30);

        tahugenjrot1.setText("Tahu Genjrot");
        tahugenjrot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahugenjrot1ActionPerformed(evt);
            }
        });
        getContentPane().add(tahugenjrot1);
        tahugenjrot1.setBounds(50, 440, 150, 30);
        getContentPane().add(tahutek);
        tahutek.setBounds(200, 240, 180, 30);

        rujak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rujakActionPerformed(evt);
            }
        });
        getContentPane().add(rujak);
        rujak.setBounds(200, 190, 180, 30);
        getContentPane().add(blendrang);
        blendrang.setBounds(200, 340, 180, 30);
        getContentPane().add(tahulontong);
        tahulontong.setBounds(200, 290, 180, 30);
        getContentPane().add(bayar);
        bayar.setBounds(400, 600, 200, 40);
        getContentPane().add(nasibantingan);
        nasibantingan.setBounds(200, 390, 180, 30);
        getContentPane().add(escaon);
        escaon.setBounds(730, 240, 180, 30);
        getContentPane().add(kopi);
        kopi.setBounds(730, 190, 180, 30);
        getContentPane().add(BTT);
        BTT.setBounds(450, 240, 70, 30);
        getContentPane().add(BR);
        BR.setBounds(450, 190, 70, 30);
        getContentPane().add(BBT);
        BBT.setBounds(450, 340, 70, 30);
        getContentPane().add(BTL);
        BTL.setBounds(450, 290, 70, 30);
        getContentPane().add(BTG);
        BTG.setBounds(450, 440, 70, 30);
        getContentPane().add(BNB);
        BNB.setBounds(450, 390, 70, 30);
        getContentPane().add(MEC);
        MEC.setBounds(980, 240, 70, 30);
        getContentPane().add(MK);
        MK.setBounds(980, 190, 70, 30);

        kopi1.setText("Kopi");
        kopi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kopi1ActionPerformed(evt);
            }
        });
        getContentPane().add(kopi1);
        kopi1.setBounds(600, 190, 120, 30);

        escaon1.setText("Es Caon");
        escaon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escaon1ActionPerformed(evt);
            }
        });
        getContentPane().add(escaon1);
        escaon1.setBounds(600, 240, 130, 30);

        tehtawar1.setText("Teh Tawar");
        tehtawar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehtawar1ActionPerformed(evt);
            }
        });
        getContentPane().add(tehtawar1);
        tehtawar1.setBounds(600, 290, 130, 30);

        aqua1.setText("Aqua");
        aqua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aqua1ActionPerformed(evt);
            }
        });
        getContentPane().add(aqua1);
        aqua1.setBounds(600, 340, 120, 30);

        esoyen1.setText("Es Oyen");
        esoyen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esoyen1ActionPerformed(evt);
            }
        });
        getContentPane().add(esoyen1);
        esoyen1.setBounds(600, 390, 130, 30);

        espisangijo1.setText("Es Pisang ijo");
        espisangijo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espisangijo1ActionPerformed(evt);
            }
        });
        getContentPane().add(espisangijo1);
        espisangijo1.setBounds(600, 440, 120, 30);
        getContentPane().add(aqua);
        aqua.setBounds(730, 340, 180, 30);
        getContentPane().add(tehtawar);
        tehtawar.setBounds(730, 290, 180, 30);
        getContentPane().add(espisangijo);
        espisangijo.setBounds(730, 440, 180, 30);
        getContentPane().add(esoyen);
        esoyen.setBounds(730, 390, 180, 30);
        getContentPane().add(MA);
        MA.setBounds(980, 340, 70, 30);
        getContentPane().add(MTT);
        MTT.setBounds(980, 290, 70, 30);
        getContentPane().add(MEPI);
        MEPI.setBounds(980, 440, 70, 30);
        getContentPane().add(MEO);
        MEO.setBounds(980, 390, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" MAKANAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 150, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("X");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 240, 30, 30);
        getContentPane().add(tahugenjrot);
        tahugenjrot.setBounds(200, 440, 180, 30);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("HAPUS");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(730, 580, 120, 40);

        bt_total.setBackground(new java.awt.Color(51, 51, 255));
        bt_total.setForeground(new java.awt.Color(255, 255, 255));
        bt_total.setText("TOTAL");
        bt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_totalActionPerformed(evt);
            }
        });
        getContentPane().add(bt_total);
        bt_total.setBounds(260, 530, 120, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BAYAR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 600, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("X");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 190, 30, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("X");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 340, 30, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("X");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 290, 30, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("X");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 390, 30, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("X");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 440, 30, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("X");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(940, 240, 30, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("X");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(940, 190, 30, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("X");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(940, 340, 30, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("X");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(940, 290, 30, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("X");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(940, 390, 30, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("X");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(940, 440, 30, 30);
        getContentPane().add(total);
        total.setBounds(400, 530, 200, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MINUMAN");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(580, 150, 110, 30);

        bt_kembalian.setBackground(new java.awt.Color(51, 51, 255));
        bt_kembalian.setForeground(new java.awt.Color(255, 255, 255));
        bt_kembalian.setText("KEMBALIAN");
        bt_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kembalianActionPerformed(evt);
            }
        });
        getContentPane().add(bt_kembalian);
        bt_kembalian.setBounds(260, 670, 120, 40);
        getContentPane().add(kembalian);
        kembalian.setBounds(400, 660, 200, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jadul's Cafe");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 0, 240, 100);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(0, 490, 1100, 26);

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(880, 580, 120, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon("F:\\234.PNG")); // NOI18N
        jLabel18.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel18.setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(280, 0, 140, 100);

        jLabel17.setIcon(new javax.swing.ImageIcon("F:\\567.PNG")); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(670, 0, 100, 110);
        getContentPane().add(jSlider2);
        jSlider2.setBounds(0, 110, 1100, 26);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 130);
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 120, 1100, 380);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 500, 1110, 240);

        setBounds(0, 0, 1106, 767);
    }// </editor-fold>//GEN-END:initComponents

    private void rujakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rujakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rujakActionPerformed

    private void kopi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kopi1ActionPerformed
        // TODO add your handling code here:
           int kopii=3000;
        if(kopi1.isSelected())
        {
            kopi.setText("" +kopi1.getText());
            kopi.setText("" +kopii);
            kopi.setEditable(false);
        }
        
        else
        {
            kopi.setText("");
            MK.setText("");
            kopi.setEditable(false);
        }
    }//GEN-LAST:event_kopi1ActionPerformed

    private void bt_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kembalianActionPerformed
        // TODO add your handling code here:
        String bayarr = bayar.getText();
        int bayars=Integer.parseInt(bayarr);
        
        String totall = total.getText();
        int totals=Integer.parseInt(totall);
        
        int kembali = bayars-totals;
        
       kembalian.setText("" + kembali);
    }//GEN-LAST:event_bt_kembalianActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
         rujak.setEditable(false);
         tahutek.setEditable(false);
         tahulontong.setEditable(false);
         blendrang.setEditable(false);
         nasibantingan.setEditable(false);
         tahugenjrot.setEditable(false);
         kopi.setEditable(false);
         escaon.setEditable(false);
         tehtawar.setEditable(false);
         aqua.setEditable(false);
         esoyen.setEditable(false);
         espisangijo.setEditable(false);                
         BR.setText("");
         BTT.setText("");
         BTL.setText("");
         BBT.setText("");
         BNB.setText("");
         BTG.setText("");
         MK.setText("");
         MEC.setText("");
         MTT.setText("");
         MA.setText("");
         MEO.setText("");
         MEPI.setText("");
         total.setText("");
         bayar.setText("");
         kembalian.setText("");
    
    }//GEN-LAST:event_clearActionPerformed

    private void rujak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rujak1ActionPerformed
        // TODO add your handling code here:
         int rujakk=5000;
        if(rujak1.isSelected())
        {
            rujak.setText("" +rujak1.getText());
            rujak.setText("" +rujakk);
            rujak.setEditable(false);
        }
        
        else
        {
            rujak.setText("");
            BR.setText("");
            rujak.setEditable(false);
        }   
    }//GEN-LAST:event_rujak1ActionPerformed

    private void tahutek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahutek1ActionPerformed
        // TODO add your handling code here:  
          int tahutekk=9000;
        if(tahutek1.isSelected())
        {
            tahutek.setText("" +tahutek1.getText());
            tahutek.setText("" +tahutekk);
            tahutek.setEditable(false);
        }
        
        else
        {
            tahutek.setText("");
            BTT.setText("");
            tahutek.setEditable(false);
        }
    }//GEN-LAST:event_tahutek1ActionPerformed

    private void tahulontong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahulontong1ActionPerformed
        // TODO add your handling code here:
          int tahulontongg=10000;
        if(tahulontong1.isSelected())
        {
            tahulontong.setText("" +tahulontong1.getText());
            tahulontong.setText("" +tahulontongg);
            tahulontong.setEditable(false);
        }
        
        else
        {
            tahulontong.setText("");
            BTL.setText("");
            tahulontong.setEditable(false);
        }
    }//GEN-LAST:event_tahulontong1ActionPerformed

    private void blendrang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blendrang1ActionPerformed
        // TODO add your handling code here:
         int blendrangg=7000;
        if(blendrang1.isSelected())
        {
            blendrang.setText("" +blendrang1.getText());
            blendrang.setText("" +blendrangg);
            blendrang.setEditable(false);
        }
        
        else
        {
            blendrang.setText("");
            BBT.setText("");
            blendrang.setEditable(false);
        }
    }//GEN-LAST:event_blendrang1ActionPerformed

    private void nasibantingan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasibantingan1ActionPerformed
        // TODO add your handling code here:
          int nasibantingg=10000;
        if(nasibantingan1.isSelected())
        {
            nasibantingan.setText("" +nasibantingan1.getText());
            nasibantingan.setText("" +nasibantingg);
            nasibantingan.setEditable(false);
        }
        
        else
        {
            nasibantingan.setText("");
            BNB.setText("");
            nasibantingan.setEditable(false);
        }
    }//GEN-LAST:event_nasibantingan1ActionPerformed

    private void tahugenjrot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahugenjrot1ActionPerformed
        // TODO add your handling code here:
           int tahugenjrott=7000;
        if(tahugenjrot1.isSelected())
        {
            tahugenjrot.setText("" +tahugenjrot1.getText());
            tahugenjrot.setText("" +tahugenjrott);
            tahugenjrot.setEditable(false);
        }
        
        else
        {
            tahugenjrot.setText("");
            BTG.setText("");
            tahugenjrot.setEditable(false);
        }
    }//GEN-LAST:event_tahugenjrot1ActionPerformed

    private void escaon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escaon1ActionPerformed
        // TODO add your handling code here:
            int escaonn=4000;
        if(escaon1.isSelected())
        {
            escaon.setText("" +escaon1.getText());
            escaon.setText("" +escaonn);
            escaon.setEditable(false);
        }
        
        else
        {
            escaon.setText("");
            MEC.setText("");
            escaon.setEditable(false);
        }
    }//GEN-LAST:event_escaon1ActionPerformed

    private void tehtawar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehtawar1ActionPerformed
        // TODO add your handling code here:
            int tehtawarr=2500;
        if(tehtawar1.isSelected())
        {
            tehtawar.setText("" +tehtawar.getText());
            tehtawar.setText("" +tehtawarr);
            tehtawar.setEditable(false);
        }
        
        else
        {
            tehtawar.setText("");
            MTT.setText("");
            tehtawar.setEditable(false);
        }
    }//GEN-LAST:event_tehtawar1ActionPerformed

    private void aqua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aqua1ActionPerformed
        // TODO add your handling code here:
             int aquaa=500;
        if(aqua1.isSelected())
        {
            aqua.setText("" +aqua1.getText());
            aqua.setText("" +aquaa);
            aqua.setEditable(false);
        }
        
        else
        {
            aqua.setText("");
            MA.setText("");
            aqua.setEditable(false);
        }
    }//GEN-LAST:event_aqua1ActionPerformed

    private void esoyen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esoyen1ActionPerformed
        // TODO add your handling code here:
            int esoyenn=3000;
        if(esoyen1.isSelected())
        {
            esoyen.setText("" +esoyen1.getText());
            esoyen.setText("" +esoyenn);
            esoyen.setEditable(false);
        }
        
        else
        {
            esoyen.setText("");
            MEO.setText("");
            esoyen.setEditable(false);
        }
    }//GEN-LAST:event_esoyen1ActionPerformed

    private void espisangijo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espisangijo1ActionPerformed
        // TODO add your handling code here:
            int espisangijoo=6000;
        if(espisangijo1.isSelected())
        {
            espisangijo.setText("" +espisangijo1.getText());
            espisangijo.setText("" +espisangijoo);
            espisangijo.setEditable(false);
        }
        
        else
        {
            espisangijo.setText("");
            MEPI.setText("");
            espisangijo.setEditable(false);
        }
    }//GEN-LAST:event_espisangijo1ActionPerformed

    private void bt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_totalActionPerformed
        // TODO add your handling code here:
         int total1=0;
         
        if (rujak1.isSelected())
          {

            String Rujaks=BR.getText();

            int BR=Integer.parseInt(Rujaks);

            int harga_rujak=BR*5000;
            total1=total1+harga_rujak;
          }
        
         if (tahutek1.isSelected())
          {

            String teks=BTT.getText();

            int BTT=Integer.parseInt(teks);

            int harga_teks=BTT*9000;
            total1=total1+harga_teks;
          }
         
         if (tahulontong1.isSelected())
          {

            String lontong=BTL.getText();

            int BTL=Integer.parseInt(lontong);

            int harga_lontong=BTL*10000;
            total1=total1+harga_lontong;
          }
          
           if (blendrang1.isSelected())
          {

            String tewel=BBT.getText();

            int BBT=Integer.parseInt(tewel);

            int harga_tewel=BBT*7000;
            total1=total1+harga_tewel;
          }
        
         if (nasibantingan1.isSelected())
          {

            String bantingan=BNB.getText();

            int BNB=Integer.parseInt(bantingan);

            int harga_bantingan=BNB*10000;
            total1=total1+harga_bantingan;
          }
         
         if (tahugenjrot1.isSelected())
          {

            String genjrot=BTG.getText();

            int BTG=Integer.parseInt(genjrot);

            int harga_genjrot=BTG*7000;
            total1=total1+harga_genjrot;
          }
        
         if (kopi1.isSelected())
          {

            String kopis=MK.getText();

            int MK=Integer.parseInt(kopis);

            int harga_kopi=MK*3000;
            total1=total1+harga_kopi;
          }
         
          if (escaon1.isSelected())
          {

            String caon=MEC.getText();

            int MEC=Integer.parseInt(caon);

            int harga_caon=MEC*4000;
            total1=total1+harga_caon;
          }
          
          if (tehtawar1.isSelected())
          {

            String tawar=MTT.getText();

            int MTT=Integer.parseInt(tawar);

            int harga_tawar=MTT*2500;
            total1=total1+harga_tawar;
          }
          
         if (aqua1.isSelected())
          {

            String aquas=MA.getText();

            int MA=Integer.parseInt(aquas);

            int harga_aqua=MA*500;
            total1=total1+harga_aqua;
          }
         
         if (esoyen1.isSelected())
          {

            String oyen=MEO.getText();

            int MEO=Integer.parseInt(oyen);

            int harga_oyen=MEO*3000;
            total1=total1+harga_oyen;
          }
         
         if (espisangijo1.isSelected())
          {

            String ijo=MEPI.getText();

            int MEPI=Integer.parseInt(ijo);

            int harga_ijo=MEPI*6000;
            total1=total1+harga_ijo;
          }
          
          total.setText("" +total1); 
    }//GEN-LAST:event_bt_totalActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         int X= JOptionPane.showConfirmDialog(null,"Keluar Program","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(X==JOptionPane.YES_OPTION)
        {
            //System.exit(0);
            dispose();
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BBT;
    private javax.swing.JTextField BNB;
    private javax.swing.JTextField BR;
    private javax.swing.JTextField BTG;
    private javax.swing.JTextField BTL;
    private javax.swing.JTextField BTT;
    private javax.swing.JTextField MA;
    private javax.swing.JTextField MEC;
    private javax.swing.JTextField MEO;
    private javax.swing.JTextField MEPI;
    private javax.swing.JTextField MK;
    private javax.swing.JTextField MTT;
    private javax.swing.JTextField aqua;
    private javax.swing.JRadioButton aqua1;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField blendrang;
    private javax.swing.JRadioButton blendrang1;
    private javax.swing.JButton bt_kembalian;
    private javax.swing.JButton bt_total;
    private javax.swing.JButton clear;
    private javax.swing.JTextField escaon;
    private javax.swing.JRadioButton escaon1;
    private javax.swing.JTextField esoyen;
    private javax.swing.JRadioButton esoyen1;
    private javax.swing.JTextField espisangijo;
    private javax.swing.JRadioButton espisangijo1;
    private javax.swing.JButton exit;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kopi;
    private javax.swing.JRadioButton kopi1;
    private javax.swing.JTextField nasibantingan;
    private javax.swing.JRadioButton nasibantingan1;
    private javax.swing.JTextField rujak;
    private javax.swing.JRadioButton rujak1;
    private javax.swing.JTextField tahugenjrot;
    private javax.swing.JRadioButton tahugenjrot1;
    private javax.swing.JTextField tahulontong;
    private javax.swing.JRadioButton tahulontong1;
    private javax.swing.JTextField tahutek;
    private javax.swing.JRadioButton tahutek1;
    private javax.swing.JTextField tehtawar;
    private javax.swing.JRadioButton tehtawar1;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
